import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {TRPCProvider} from "@/trpc/client";

const inter = Inter({
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider afterSignOutUrl={"/"}>
            <html lang="en">
                <body
                    className={`${inter.className} bg-gray-50 text-gray-950 dark:bg-gray-900 dark:text-gray-50`}
                >
                <TRPCProvider>
                    {children}
                </TRPCProvider>
                </body>
            </html>
        </ClerkProvider>

);
}
